### PR TITLE
Add about-copy.md and activities-copy.md

### PR DESCRIPTION
**Pull request by briancmlee**

### CODE REVIEW

**Comment by briancmlee** [comment]
Please review PR; Don't delete branch after merge

**Review by abinxzh — COMMENTED** [review]
Have made changes. Please read over before giving a final approval.

**Comment by briancmlee** [comment]
Looks great, changes approved. In the future, please make changes in a new branch and request merge

**Review by abinxzh — CHANGES_REQUESTED** [review]
About-copy.md should be formatted to match the formatting of activities-copy.md

**Review by briancmlee — COMMENTED** [review]
Changes have been made so that formatting matches

**Review by abinxzh — APPROVED** [review]

**Pull request merged**
